//! Automated markdown audit report generator (`sat audit`).
//!
//! Turns a full static analysis into a professional audit report:
//! a metadata header, an executive summary with severity and confidence
//! distributions, findings grouped by SARIF rule id, an optional
//! transaction-report correlation section, and a fixed scope/limitations
//! section that mirrors the honest-limitations model of
//! `docs/EXPLOIT_CORPUS.md`.
//!
//! [`render_markdown`] is pure and side-effect free (fully testable);
//! [`run`] wires it to [`crate::analyzer::collect`] and writes the report
//! to disk. The orchestrator wires the CLI — wiring this module is exactly:
//!
//! ```text
//! // crates/sat/src/lib.rs
//! pub mod audit;
//! // crates/sat/src/main.rs
//! mod audit;
//! ```

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

use crate::analyzer;
use crate::sarif;
use crate::types::{Confidence, Finding, Severity};
use crate::ui;

/// Fixed "Scope & Honest Limitations" section. Mirrors the documented
/// limitations of `docs/EXPLOIT_CORPUS.md` and is kept identical across
/// every generated report.
const LIMITATIONS_SECTION: &str = "## Scope & Honest Limitations

This report is generated by static analysis of the program source. Every
finding is a lead, not proof of exploitability: `sat` inspects declared
constraints and source patterns, never runtime behavior. The absence of a
finding is therefore not an assertion of security, and each finding
requires manual verification before being submitted to an audit or bounty
program.

The following classes are explicitly out of scope for this static backend,
mirroring the documented limitations of `docs/EXPLOIT_CORPUS.md`:

- **Semantic field-level invariants** — a field may be validated, but not
  for the right invariant (e.g. an unchecked identity field inside a
  manually validated account chain).
- **Oracle economics** — price-feed manipulation, TWAP/confidence-interval
  reasoning, and liquidation math are protocol-specific concerns outside
  per-instruction pattern analysis.
- **Cross-instruction atomicity** — multi-transaction flows, replay
  protection (e.g. consumed-VAA tracking), and closed-account revival
  across instructions.
- **Governance logic** — post-exploit governance consequences and
  multi-sig / upgrade orchestration.

Per-finding manual verification steps are included in the Findings section.
A finding becomes actionable only after a human confirms the flagged
pattern is reachable and exploitable on the deployed program.
";

/// Renders the full markdown audit report for a set of findings.
///
/// Pure function: no I/O, no randomness, no mutable global state (only the
/// wall-clock generated date via `chrono`). Output structure:
///
/// - `# Audit Report — <program>` header with a metadata block (generated
///   date `%Y-%m-%d`, program id when known, finding count, rule count).
/// - `## Executive Summary` with severity counts and confidence
///   distribution derived from [`Finding::confidence`].
/// - `## Findings` grouped by rule id ([`sarif::classify_finding_rule`]),
///   then by severity descending, each finding as a definition-list block.
/// - `## Transaction Report Correlation` only when `tx_report_path` is set.
/// - `## Scope & Honest Limitations` (fixed section).
pub fn render_markdown(
    findings: &[Finding],
    program_name: &str,
    program_id: Option<&str>,
    tx_report_path: Option<&str>,
) -> String {
    let mut md = String::new();

    render_header(&mut md, findings, program_name, program_id);
    render_executive_summary(&mut md, findings);
    render_findings_section(&mut md, findings);
    render_tx_report_section(&mut md, tx_report_path);
    md.push_str(LIMITATIONS_SECTION);
    md.push('\n');

    md
}

/// Runs the full analysis pipeline and writes the markdown audit report.
///
/// Program identity resolution order: Anchor IDL name (with `metadata.address`
/// as the program id), else the native program's `program_id`, else the source
/// path stem. The report is written to `out_path` or `audit-report.md` in the
/// current working directory.
pub fn run(src_path: Option<&str>, out_path: Option<&str>, tx_report: Option<&str>) -> Result<()> {
    let output = analyzer::collect(src_path, tx_report, None)?;

    if output.parsed_files.is_empty() {
        anyhow::bail!(
            "No Rust source files could be parsed under {:?}. Pass an existing program directory or file.",
            src_path.unwrap_or("<default source search>")
        );
    }

    let (program_name, program_id) = resolve_program_identity(&output, src_path);

    let markdown = render_markdown(&output.findings, &program_name, program_id.as_deref(), tx_report);

    let report_path = out_path.unwrap_or("audit-report.md");
    fs::write(report_path, markdown).with_context(|| format!("Failed to write audit report to {report_path}"))?;

    ui::print_success(&format!(
        "Audit report written to {report_path} ({program_name}, {} finding(s)).",
        output.findings.len()
    ));

    Ok(())
}

// ── Report sections ───────────────────────────────────────────────────────────

fn render_header(md: &mut String, findings: &[Finding], program_name: &str, program_id: Option<&str>) {
    md.push_str(&format!("# Audit Report \u{2014} {program_name}\n\n"));
    md.push_str("| Field | Value |\n| --- | --- |\n");
    md.push_str(&format!("| Program | `{program_name}` |\n"));
    if let Some(pid) = program_id {
        md.push_str(&format!("| Program ID | `{pid}` |\n"));
    }
    let generated = chrono::Local::now().format("%Y-%m-%d");
    md.push_str(&format!("| Generated | {generated} |\n"));
    md.push_str(&format!("| Findings | {} |\n", findings.len()));
    md.push_str(&format!("| Rules | {} |\n\n", distinct_rule_count(findings)));
}

fn render_executive_summary(md: &mut String, findings: &[Finding]) {
    md.push_str("## Executive Summary\n\n");

    md.push_str("| Severity | Count |\n| --- | --- |\n");
    for severity in [Severity::Critical, Severity::High, Severity::Medium, Severity::Low, Severity::Informational] {
        let count = findings.iter().filter(|f| f.severity == severity).count();
        md.push_str(&format!("| {severity} | {count} |\n"));
    }

    md.push_str("\n| Confidence | Count |\n| --- | --- |\n");
    for confidence in [Confidence::High, Confidence::Medium, Confidence::Low] {
        let count = findings.iter().filter(|f| f.confidence() == confidence).count();
        md.push_str(&format!("| {confidence} | {count} |\n"));
    }

    md.push('\n');
}

fn render_findings_section(md: &mut String, findings: &[Finding]) {
    md.push_str("## Findings\n\n");

    if findings.is_empty() {
        md.push_str(
            "No findings were produced by static analysis. This is not an assertion of security \
                     — see the Scope & Honest Limitations section below.\n\n",
        );
        return;
    }

    // Group by rule id (sorted), then severity descending, preserving the
    // original order within a severity bucket.
    let mut by_rule: BTreeMap<String, Vec<&Finding>> = BTreeMap::new();
    for finding in findings {
        by_rule.entry(sarif::classify_finding_rule(finding)).or_default().push(finding);
    }
    for rule_findings in by_rule.values_mut() {
        rule_findings.sort_by_key(|f| std::cmp::Reverse(severity_rank(f.severity)));
        for finding in rule_findings {
            render_finding(md, finding);
        }
    }
}

fn render_finding(md: &mut String, finding: &Finding) {
    let rule = sarif::classify_finding_rule(finding);

    md.push_str(&format!("### {} \u{2014} {}\n\n", finding.id, finding.title));
    md.push_str(&format!("**Severity:** {}\n", finding.severity));
    md.push_str(&format!("**Confidence:** {}\n", finding.confidence()));
    md.push_str(&format!("**Rule:** {rule}\n"));

    if let Some(location) = &finding.location {
        md.push_str(&format!("\n**Location:** `{location}`\n"));
    }

    let affected = finding.affected_accounts();
    if !affected.is_empty() {
        md.push_str(&format!("\n**Affected accounts:** {}\n", affected.join(", ")));
    }

    md.push_str("\n**Description:**\n\n");
    md.push_str(&finding.description);
    md.push('\n');

    if let Some(suggestion) = &finding.suggestion {
        md.push_str("\n**Suggestion:**\n\n");
        md.push_str(suggestion);
        md.push('\n');
    }

    let steps = finding.manual_verification_steps();
    if !steps.is_empty() {
        md.push_str("\n**Manual verification:**\n\n");
        for (index, step) in steps.iter().enumerate() {
            md.push_str(&format!("{}. {step}\n", index + 1));
        }
    }

    md.push('\n');
}

fn render_tx_report_section(md: &mut String, tx_report_path: Option<&str>) {
    if let Some(path) = tx_report_path {
        md.push_str("## Transaction Report Correlation\n\n");
        md.push_str(&format!(
            "The findings in this report include **SAT011** correlation checks performed against the \
             on-chain transaction report at `{path}`. These findings compare declared account \
             constraints with observed runtime behavior from the transaction report. Correlation \
             results are strong leads, but each flagged account must still be confirmed against the \
             program source and a live replay before submission.\n\n"
        ));
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Distinct rule id count across findings, using the same rule classifier
/// the SARIF exporter and the per-finding blocks use.
fn distinct_rule_count(findings: &[Finding]) -> usize {
    let mut rules = BTreeSet::new();
    for finding in findings {
        rules.insert(sarif::classify_finding_rule(finding));
    }
    rules.len()
}

/// Descending severity order: Critical (5) through Informational (1).
fn severity_rank(severity: Severity) -> u8 {
    match severity {
        Severity::Critical => 5,
        Severity::High => 4,
        Severity::Medium => 3,
        Severity::Low => 2,
        Severity::Informational => 1,
    }
}

/// Resolves the report's program identity: Anchor IDL name (with
/// `metadata.address` as program id), else the native program id, else the
/// source path stem (or `program` when none is derivable).
fn resolve_program_identity(output: &analyzer::AnalysisOutput, src_path: Option<&str>) -> (String, Option<String>) {
    if let Some(idl) = &output.ctx.idl {
        let program_id = idl.metadata.as_ref().and_then(|meta| meta.address.clone());
        return (idl.name.clone(), program_id);
    }

    if let Some(program_id) = output.native_program.as_ref().and_then(|program| program.program_id.clone()) {
        return (program_id.clone(), Some(program_id));
    }

    let stem = src_path
        .map(Path::new)
        .and_then(|path| path.file_stem())
        .and_then(|stem| stem.to_str())
        .filter(|stem| !stem.is_empty())
        .unwrap_or("program");
    (stem.to_string(), None)
}
