//! Automated markdown audit report generator (`sat audit`).
//!
//! Turns a full static analysis into a professional audit report:
//! a metadata header, an executive summary with severity and confidence
//! distributions, findings grouped by SARIF rule id, an optional
//! transaction-report correlation section, and a fixed scope/limitations
//! section that mirrors the honest-limitations model of
//! `docs/EXPLOIT_CORPUS.md`.
//!
//! [`render_markdown`] is pure and side-effect free (fully testable);
//! [`run`] wires it to [`crate::analyzer::collect`] and writes the report
//! to disk. The orchestrator wires the CLI — wiring this module is exactly:
//!
//! ```text
//! // crates/sat/src/lib.rs
//! pub mod audit;
//! // crates/sat/src/main.rs
//! mod audit;
//! ```

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

use crate::analyzer;
use crate::sarif;
use crate::types::{Confidence, Finding, Severity};
use crate::ui;

/// Fixed "Scope & Honest Limitations" section. Mirrors the documented
/// limitations of `docs/EXPLOIT_CORPUS.md` and is kept identical across
/// every generated report.
const LIMITATIONS_SECTION: &str = "## Scope & Honest Limitations

This report is generated by static analysis of the program source. Every
finding is a lead, not proof of exploitability: `sat` inspects declared
constraints and source patterns, never runtime behavior. The absence of a
finding is therefore not an assertion of security, and each finding
requires manual verification before being submitted to an audit or bounty
program.

The following classes are explicitly out of scope for this static backend,
mirroring the documented limitations of `docs/EXPLOIT_CORPUS.md`:

- **Semantic field-level invariants** — a field may be validated, but not
  for the right invariant (e.g. an unchecked identity field inside a
  manually validated account chain).
- **Oracle economics** — price-feed manipulation, TWAP/confidence-interval
  reasoning, and liquidation math are protocol-specific concerns outside
  per-instruction pattern analysis.
- **Cross-instruction atomicity** — multi-transaction flows, replay
  protection (e.g. consumed-VAA tracking), and closed-account revival
  across instructions.
- **Governance logic** — post-exploit governance consequences and
  multi-sig / upgrade orchestration.

Per-finding manual verification steps are included in the Findings section.
A finding becomes actionable only after a human confirms the flagged
pattern is reachable and exploitable on the deployed program.
";

/// Renders the full markdown audit report for a set of findings.
///
/// Pure function: no I/O, no randomness, no mutable global state (only the
/// wall-clock generated date via `chrono`). Output structure:
///
/// - `# Audit Report — <program>` header with a metadata block (generated
///   date `%Y-%m-%d`, program id when known, finding count, rule count).
/// - `## Executive Summary` with severity counts and confidence
///   distribution derived from [`Finding::confidence`].
/// - `## Findings` grouped by rule id ([`sarif::classify_finding_rule`]),
///   then by severity descending, each finding as a definition-list block.
/// - `## Transaction Report Correlation` only when `tx_report_path` is set.
/// - `## Scope & Honest Limitations` (fixed section).
pub fn render_markdown(
    findings: &[Finding],
    program_name: &str,
    program_id: Option<&str>,
    tx_report_path: Option<&str>,
) -> String {
    let mut md = String::new();

    render_header(&mut md, findings, program_name, program_id);
    render_executive_summary(&mut md, findings);
    render_findings_section(&mut md, findings);
    render_tx_report_section(&mut md, tx_report_path);
    md.push_str(LIMITATIONS_SECTION);
    md.push('\n');

    md
}

/// Fixed "Scope & Honest Limitations" section as HTML (mirrors the markdown
/// constant). Kept in sync with `LIMITATIONS_SECTION`.
const LIMITATIONS_HTML: &str = r#"<section class="limitations">
<h2>Scope &amp; Honest Limitations</h2>
<p>This report is generated by static analysis of the program source. Every finding is a <strong>lead, not proof of exploitability</strong>: <code>sat</code> inspects declared constraints and source patterns, never runtime behavior. The absence of a finding is therefore not an assertion of security, and each finding requires manual verification before being submitted to an audit or bounty program.</p>
<p>The following classes are explicitly out of scope for this static backend, mirroring the documented limitations of <code>docs/EXPLOIT_CORPUS.md</code>:</p>
<ul>
<li><strong>Semantic field-level invariants</strong> — a field may be validated, but not for the right invariant.</li>
<li><strong>Oracle economics</strong> — price-feed manipulation, TWAP/confidence-interval reasoning, and liquidation math are protocol-specific concerns outside per-instruction pattern analysis.</li>
<li><strong>Cross-instruction atomicity</strong> — multi-transaction flows, replay protection, and closed-account revival across instructions.</li>
<li><strong>Governance logic</strong> — post-exploit governance consequences and multi-sig / upgrade orchestration.</li>
</ul>
<p>Per-finding manual verification steps are included above. A finding becomes actionable only after a human confirms the flagged pattern is reachable and exploitable on the deployed program.</p>
</section>"#;

const HTML_STYLE: &str = r#"
:root{--bg:#0f1115;--panel:#171a21;--fg:#e6e6e6;--muted:#9aa4b2;--line:#2a2f3a;
--crit:#ff4d4f;--high:#ff7a45;--med:#ffc53d;--low:#36cfc9;--info:#8c8c8c;--accent:#7c5cff;}
*{box-sizing:border-box}
body{margin:0;font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
background:var(--bg);color:var(--fg)}
main{max-width:960px;margin:0 auto;padding:32px 20px 80px}
header h1{margin:0 0 8px;font-size:26px}
.meta{color:var(--muted);font-size:14px}
.meta code{color:var(--fg)}
h2{margin-top:36px;border-bottom:1px solid var(--line);padding-bottom:6px}
table{border-collapse:collapse;width:100%;margin:12px 0}
th,td{border:1px solid var(--line);padding:8px 12px;text-align:left}
th{background:var(--panel);color:var(--muted);font-weight:600}
.finding{background:var(--panel);border:1px solid var(--line);border-left:4px solid var(--muted);
border-radius:8px;padding:16px 18px;margin:16px 0}
.finding.critical{border-left-color:var(--crit)}.finding.high{border-left-color:var(--high)}
.finding.medium{border-left-color:var(--med)}.finding.low{border-left-color:var(--low)}
.finding.informational{border-left-color:var(--info)}
.finding h3{margin:0 0 6px;font-size:17px}
.badge{display:inline-block;font-size:12px;font-weight:700;padding:2px 8px;border-radius:999px;
margin-right:8px;color:#000}
.badge.critical{background:var(--crit)}.badge.high{background:var(--high)}
.badge.medium{background:var(--med)}.badge.low{background:var(--low)}.badge.informational{background:var(--info)}
.rule{color:var(--accent);font-weight:600}
.loc{color:var(--muted);font-size:13px;word-break:break-all}
pre{background:#0b0d11;border:1px solid var(--line);border-radius:6px;padding:10px;overflow:auto;white-space:pre-wrap}
.limitations{color:var(--muted)}
.limitations code{color:var(--fg)}
"#;

/// Renders a **self-contained** HTML audit report (embedded CSS, no external
/// assets) from the same data as [`render_markdown`]. Suitable as a client
/// deliverable or an artifact upload.
pub fn render_html(
    findings: &[Finding],
    program_name: &str,
    program_id: Option<&str>,
    tx_report_path: Option<&str>,
) -> String {
    let mut h = String::new();
    h.push_str("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n");
    h.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    h.push_str(&format!("<title>Audit Report — {}</title>\n", escape_html(program_name)));
    h.push_str(&format!("<style>{HTML_STYLE}</style>\n</head>\n<body>\n<main>\n"));

    // Header + metadata.
    h.push_str(&format!("<header><h1>Audit Report — {}</h1>\n<div class=\"meta\">\n", escape_html(program_name)));
    if let Some(pid) = program_id {
        h.push_str(&format!("Program ID: <code>{}</code><br>\n", escape_html(pid)));
    }
    h.push_str(&format!(
        "Generated: {} &middot; Findings: {} &middot; Rules: {}\n</div></header>\n",
        chrono::Local::now().format("%Y-%m-%d"),
        findings.len(),
        distinct_rule_count(findings)
    ));

    // Executive summary.
    h.push_str(
        "<section><h2>Executive Summary</h2>\n<table><thead><tr><th>Severity</th><th>Count</th></tr></thead><tbody>\n",
    );
    for severity in [Severity::Critical, Severity::High, Severity::Medium, Severity::Low, Severity::Informational] {
        let count = findings.iter().filter(|f| f.severity == severity).count();
        h.push_str(&format!(
            "<tr><td><span class=\"badge {}\">{}</span></td><td>{}</td></tr>\n",
            severity.to_string().to_ascii_lowercase(),
            severity,
            count
        ));
    }
    h.push_str("</tbody></table>\n");
    h.push_str("<table><thead><tr><th>Confidence</th><th>Count</th></tr></thead><tbody>\n");
    for confidence in [Confidence::High, Confidence::Medium, Confidence::Low] {
        let count = findings.iter().filter(|f| f.confidence() == confidence).count();
        h.push_str(&format!("<tr><td>{confidence}</td><td>{count}</td></tr>\n"));
    }
    h.push_str("</tbody></table></section>\n");

    // Findings.
    h.push_str("<section><h2>Findings</h2>\n");
    if findings.is_empty() {
        h.push_str("<p>No findings were produced by static analysis. This is not an assertion of security — see Scope &amp; Honest Limitations below.</p>\n");
    } else {
        let mut by_rule: BTreeMap<String, Vec<&Finding>> = BTreeMap::new();
        for finding in findings {
            by_rule.entry(sarif::classify_finding_rule(finding)).or_default().push(finding);
        }
        for rule_findings in by_rule.values_mut() {
            rule_findings.sort_by_key(|f| std::cmp::Reverse(severity_rank(f.severity)));
            for finding in rule_findings {
                render_finding_html(&mut h, finding);
            }
        }
    }
    h.push_str("</section>\n");

    if let Some(path) = tx_report_path {
        h.push_str("<section><h2>Transaction Report Correlation</h2>\n<p>SAT011 correlation checks were performed against the on-chain transaction report at <code>");
        h.push_str(&escape_html(path));
        h.push_str("</code>. Correlation results are strong leads; each flagged account must still be confirmed against the program source and a live replay before submission.</p></section>\n");
    }

    h.push_str(LIMITATIONS_HTML);
    h.push_str("\n</main>\n</body>\n</html>\n");
    h
}

fn render_finding_html(h: &mut String, finding: &Finding) {
    let rule = sarif::classify_finding_rule(finding);
    let sev = finding.severity.to_string().to_ascii_lowercase();

    h.push_str(&format!("<article class=\"finding {sev}\">\n"));
    h.push_str(&format!(
        "<h3><span class=\"badge {sev}\">{}</span> {} — {}</h3>\n",
        finding.severity,
        escape_html(&finding.id),
        escape_html(&finding.title)
    ));
    h.push_str(&format!(
        "<div class=\"meta\"><span class=\"rule\">{}</span> &middot; Confidence: {}</div>\n",
        escape_html(&rule),
        finding.confidence()
    ));
    if let Some(location) = &finding.location {
        h.push_str(&format!("<div class=\"loc\">{}</div>\n", escape_html(location)));
    }
    let affected = finding.affected_accounts();
    if !affected.is_empty() {
        h.push_str(&format!("<p><strong>Affected accounts:</strong> {}</p>\n", escape_html(&affected.join(", "))));
    }
    h.push_str(&format!("<p><strong>Description:</strong></p>\n<pre>{}</pre>\n", escape_html(&finding.description)));
    if let Some(suggestion) = &finding.suggestion {
        h.push_str(&format!("<p><strong>Suggestion:</strong></p>\n<pre>{}</pre>\n", escape_html(suggestion)));
    }
    let steps = finding.manual_verification_steps();
    if !steps.is_empty() {
        h.push_str("<p><strong>Manual verification:</strong></p>\n<ol>\n");
        for step in &steps {
            h.push_str(&format!("<li>{}</li>\n", escape_html(step)));
        }
        h.push_str("</ol>\n");
    }
    h.push_str("</article>\n");
}

/// Minimal HTML escaping for untrusted finding text.
fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

/// Runs the full analysis pipeline and writes the audit report (`md` or `html`).
///
/// Program identity resolution order: Anchor IDL name (with `metadata.address`
/// as the program id), else the native program's `program_id`, else the source
/// path stem. The report is written to `out_path` or `audit-report.<ext>` in the
/// current working directory.
pub fn run(src_path: Option<&str>, out_path: Option<&str>, tx_report: Option<&str>, format: &str) -> Result<()> {
    let output = analyzer::collect(src_path, tx_report, None)?;

    if output.parsed_files.is_empty() {
        anyhow::bail!(
            "No Rust source files could be parsed under {:?}. Pass an existing program directory or file.",
            src_path.unwrap_or("<default source search>")
        );
    }

    let (program_name, program_id) = resolve_program_identity(&output, src_path);

    let html = format.eq_ignore_ascii_case("html");
    let report = if html {
        render_html(&output.findings, &program_name, program_id.as_deref(), tx_report)
    } else {
        render_markdown(&output.findings, &program_name, program_id.as_deref(), tx_report)
    };

    let default_name = if html { "audit-report.html" } else { "audit-report.md" };
    let report_path = out_path.unwrap_or(default_name);
    fs::write(report_path, report).with_context(|| format!("Failed to write audit report to {report_path}"))?;

    ui::print_success(&format!(
        "Audit report written to {report_path} ({program_name}, {} finding(s)).",
        output.findings.len()
    ));

    Ok(())
}

// ── Report sections ───────────────────────────────────────────────────────────

fn render_header(md: &mut String, findings: &[Finding], program_name: &str, program_id: Option<&str>) {
    md.push_str(&format!("# Audit Report \u{2014} {program_name}\n\n"));
    md.push_str("| Field | Value |\n| --- | --- |\n");
    md.push_str(&format!("| Program | `{program_name}` |\n"));
    if let Some(pid) = program_id {
        md.push_str(&format!("| Program ID | `{pid}` |\n"));
    }
    let generated = chrono::Local::now().format("%Y-%m-%d");
    md.push_str(&format!("| Generated | {generated} |\n"));
    md.push_str(&format!("| Findings | {} |\n", findings.len()));
    md.push_str(&format!("| Rules | {} |\n\n", distinct_rule_count(findings)));
}

fn render_executive_summary(md: &mut String, findings: &[Finding]) {
    md.push_str("## Executive Summary\n\n");

    md.push_str("| Severity | Count |\n| --- | --- |\n");
    for severity in [Severity::Critical, Severity::High, Severity::Medium, Severity::Low, Severity::Informational] {
        let count = findings.iter().filter(|f| f.severity == severity).count();
        md.push_str(&format!("| {severity} | {count} |\n"));
    }

    md.push_str("\n| Confidence | Count |\n| --- | --- |\n");
    for confidence in [Confidence::High, Confidence::Medium, Confidence::Low] {
        let count = findings.iter().filter(|f| f.confidence() == confidence).count();
        md.push_str(&format!("| {confidence} | {count} |\n"));
    }

    md.push('\n');
}

fn render_findings_section(md: &mut String, findings: &[Finding]) {
    md.push_str("## Findings\n\n");

    if findings.is_empty() {
        md.push_str(
            "No findings were produced by static analysis. This is not an assertion of security \
                     — see the Scope & Honest Limitations section below.\n\n",
        );
        return;
    }

    // Group by rule id (sorted), then severity descending, preserving the
    // original order within a severity bucket.
    let mut by_rule: BTreeMap<String, Vec<&Finding>> = BTreeMap::new();
    for finding in findings {
        by_rule.entry(sarif::classify_finding_rule(finding)).or_default().push(finding);
    }
    for rule_findings in by_rule.values_mut() {
        rule_findings.sort_by_key(|f| std::cmp::Reverse(severity_rank(f.severity)));
        for finding in rule_findings {
            render_finding(md, finding);
        }
    }
}

fn render_finding(md: &mut String, finding: &Finding) {
    let rule = sarif::classify_finding_rule(finding);

    md.push_str(&format!("### {} \u{2014} {}\n\n", finding.id, finding.title));
    md.push_str(&format!("**Severity:** {}\n", finding.severity));
    md.push_str(&format!("**Confidence:** {}\n", finding.confidence()));
    md.push_str(&format!("**Rule:** {rule}\n"));

    if let Some(location) = &finding.location {
        md.push_str(&format!("\n**Location:** `{location}`\n"));
    }

    let affected = finding.affected_accounts();
    if !affected.is_empty() {
        md.push_str(&format!("\n**Affected accounts:** {}\n", affected.join(", ")));
    }

    md.push_str("\n**Description:**\n\n");
    md.push_str(&finding.description);
    md.push('\n');

    if let Some(suggestion) = &finding.suggestion {
        md.push_str("\n**Suggestion:**\n\n");
        md.push_str(suggestion);
        md.push('\n');
    }

    let steps = finding.manual_verification_steps();
    if !steps.is_empty() {
        md.push_str("\n**Manual verification:**\n\n");
        for (index, step) in steps.iter().enumerate() {
            md.push_str(&format!("{}. {step}\n", index + 1));
        }
    }

    md.push('\n');
}

fn render_tx_report_section(md: &mut String, tx_report_path: Option<&str>) {
    if let Some(path) = tx_report_path {
        md.push_str("## Transaction Report Correlation\n\n");
        md.push_str(&format!(
            "The findings in this report include **SAT011** correlation checks performed against the \
             on-chain transaction report at `{path}`. These findings compare declared account \
             constraints with observed runtime behavior from the transaction report. Correlation \
             results are strong leads, but each flagged account must still be confirmed against the \
             program source and a live replay before submission.\n\n"
        ));
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Distinct rule id count across findings, using the same rule classifier
/// the SARIF exporter and the per-finding blocks use.
fn distinct_rule_count(findings: &[Finding]) -> usize {
    let mut rules = BTreeSet::new();
    for finding in findings {
        rules.insert(sarif::classify_finding_rule(finding));
    }
    rules.len()
}

/// Descending severity order: Critical (5) through Informational (1).
fn severity_rank(severity: Severity) -> u8 {
    match severity {
        Severity::Critical => 5,
        Severity::High => 4,
        Severity::Medium => 3,
        Severity::Low => 2,
        Severity::Informational => 1,
    }
}

/// Resolves the report's program identity: Anchor IDL name (with
/// `metadata.address` as program id), else the native program id, else the
/// source path stem (or `program` when none is derivable).
fn resolve_program_identity(output: &analyzer::AnalysisOutput, src_path: Option<&str>) -> (String, Option<String>) {
    if let Some(idl) = &output.ctx.idl {
        let program_id = idl.metadata.as_ref().and_then(|meta| meta.address.clone());
        return (idl.name.clone(), program_id);
    }

    if let Some(program_id) = output.native_program.as_ref().and_then(|program| program.program_id.clone()) {
        return (program_id.clone(), Some(program_id));
    }

    let stem = src_path
        .map(Path::new)
        .and_then(|path| path.file_stem())
        .and_then(|stem| stem.to_str())
        .filter(|stem| !stem.is_empty())
        .unwrap_or("program");
    (stem.to_string(), None)
}
