use std::fs;
use std::path::PathBuf;
use std::process::Command;

use anyhow::{Context, Result};

use crate::idl;
use crate::ui;

const FUZZER_DIR: &str = "fuzzer";

struct FuzzerConfig {
    program_name: String,
    program_lib_name: String,
    instructions: Vec<String>,
    has_vault: bool,
    has_token: bool,
    has_state_init_flag: bool,
}

pub fn init() -> Result<()> {
    ui::print_banner();
    ui::print_section_header("Fuzzer Initialization");

    let config = match idl::find_idl_in_workspace().ok().and_then(|p| idl::parse_idl(&p).ok()) {
        Some(idl) => {
            let program_name = idl.name.clone();
            let program_lib_name = program_name.replace('-', "_");
            let instructions: Vec<String> = idl.instructions.iter().map(|i| i.name.clone()).collect();
            let has_vault =
                program_name.contains("vault") || idl.accounts.iter().any(|a| a.name.to_lowercase().contains("vault"));
            let has_token = idl.instructions.iter().any(|ix| {
                ix.accounts
                    .iter()
                    .any(|a| a.name.to_lowercase().contains("token") || a.name.to_lowercase().contains("mint"))
            });
            let has_state_init_flag = idl.accounts.iter().any(|a| {
                a.ty.fields.iter().any(|f| {
                    let lower = f.name.to_lowercase();
                    lower == "is_initialized" || lower == "initialized" || lower == "isinitialized"
                })
            });
            FuzzerConfig { program_name, program_lib_name, instructions, has_vault, has_token, has_state_init_flag }
        }
        None => {
            ui::print_warning("No Anchor IDL found. Generating fuzzer with default configuration...");
            FuzzerConfig {
                program_name: "program".to_string(),
                program_lib_name: "program".to_string(),
                instructions: vec!["initialize".to_string(), "update".to_string(), "close".to_string()],
                has_vault: false,
                has_token: false,
                has_state_init_flag: false,
            }
        }
    };

    generate_fuzzer(&config)?;
    update_workspace_cargo()?;

    ui::print_success("Fuzzer crate generated successfully.");
    ui::print_notice(&format!("Fuzzer created at: {FUZZER_DIR}/"));
    ui::print_notice("Next steps:");
    println!("  1. cd {FUZZER_DIR}");
    println!("  2. Review fuzz_targets/instruction_fuzz.rs");
    println!("  3. Run: sat fuzz run");
    println!();
    Ok(())
}

fn generate_fuzzer(config: &FuzzerConfig) -> Result<()> {
    let dir = PathBuf::from(FUZZER_DIR);
    fs::create_dir_all(dir.join("src"))?;
    fs::create_dir_all(dir.join("fuzz_targets"))?;

    fs::write(dir.join("Cargo.toml"), render_cargo_toml(config))?;
    fs::write(dir.join("src").join("lib.rs"), render_lib_rs(config))?;
    fs::write(dir.join("fuzz_targets").join("instruction_fuzz.rs"), render_fuzz_target(config))?;
    Ok(())
}

fn render_cargo_toml(config: &FuzzerConfig) -> String {
    format!(
        r#"[package]
name = "fuzzer-{}"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
{} = {{ path = "../programs/{}", features = ["no-entrypoint"] }}
anchor-lang = "0.29"
solana-program = "4"
solana-program-test = "4"
solana-sdk = "4"
spl-token = "7"
spl-token-2022 = "7"
arbitrary = {{ version = "1", features = ["derive"] }}
rand = "0.8"
libfuzzer-sys = "0.4"
tokio = {{ version = "1", features = ["full"] }}

[[bin]]
name = "instruction_fuzz"
path = "fuzz_targets/instruction_fuzz.rs"
test = false
doc = false
"#,
        config.program_name, config.program_lib_name, config.program_lib_name
    )
}

fn render_lib_rs(config: &FuzzerConfig) -> String {
    let invariants = render_invariants(config);
    let checks = render_invariant_checks(config);
    let date = chrono::Local::now().format("%Y-%m-%d");

    format!(
        r#"// Auto-generated by `sat fuzz init` — {date}
// Program: {prog}
// Instructions: {ix_list}

use solana_program_test::{{BanksClient, ProgramTest, processor}};
use solana_sdk::{{account::Account, pubkey::Pubkey, signature::Signer, signer::keypair::Keypair, instruction::Instruction, transaction::Transaction}};
use arbitrary::Arbitrary;

const PROGRAM_ID: Pubkey = pubkey!("REPLACE_WITH_YOUR_PROGRAM_ID");

#[derive(Arbitrary, Debug, Clone)]
pub enum FuzzInstruction {{
{enum_variants}}}

impl FuzzInstruction {{
    pub fn as_ix_name(&self) -> &'static str {{
        match self {{
{ix_name_match}
        }}
    }}

    pub fn to_instruction(&self) -> Instruction {{
        match self {{
{to_ix_match}
        }}
    }}
}}

pub fn set_up_program_test() -> ProgramTest {{
    ProgramTest::new("{lib_name}", PROGRAM_ID, processor!(entry))
}}

{invariants}

pub fn check_invariants(
    _banks_client: &mut BanksClient,
    _payer: &Keypair,
    accounts_snapshot: &[(Pubkey, Account)],
    trace: &[FuzzInstruction],
) -> Result<(), Vec<String>> {{
    let mut violations = Vec::new();
{checks}
    if violations.is_empty() {{ Ok(()) }} else {{ Err(violations) }}
}}
"#,
        date = date,
        prog = config.program_name,
        ix_list = config.instructions.join(", "),
        enum_variants = render_arbitrary_enum_variants(config),
        ix_name_match = render_ix_name_match(config),
        to_ix_match = render_to_instruction_match(config),
        lib_name = config.program_lib_name,
        invariants = invariants,
        checks = checks,
    )
}

fn render_arbitrary_enum_variants(config: &FuzzerConfig) -> String {
    config.instructions.iter().map(|ix| format!("    {}(Vec<u8>),\n", to_pascal_case(ix))).collect()
}

fn render_ix_name_match(config: &FuzzerConfig) -> String {
    config
        .instructions
        .iter()
        .map(|ix| format!("            FuzzInstruction::{}(_) => \"{ix}\",\n", to_pascal_case(ix)))
        .collect()
}

fn render_to_instruction_match(config: &FuzzerConfig) -> String {
    config
        .instructions
        .iter()
        .map(|ix| {
            format!(
                "            FuzzInstruction::{}(data) => Instruction::new_with_bytes(PROGRAM_ID, data, vec![]),\n",
                to_pascal_case(ix)
            )
        })
        .collect()
}

fn render_invariants(config: &FuzzerConfig) -> String {
    let mut out = String::from("// Security Invariants\n\n");

    if config.has_token {
        out.push_str(
            "/// Token Supply Preservation\npub fn check_token_supply(before: u64, after: u64) -> Option<String> {\n    if before != after { Some(format!(\"Token supply changed: {before} -> {after}\")) } else { None }\n}\n",
        );
    }

    if config.has_vault {
        out.push_str(
            "/// Vault Balance Consistency\npub fn check_vault_consistency(vault: u64, total_deposits: u64) -> Option<String> {\n    if vault < total_deposits { Some(format!(\"Vault underfunded: vault={vault} < deposits={total_deposits}\")) } else { None }\n}\n",
        );
    }

    if config.has_token || config.has_vault {
        out.push_str(
            "/// No Negative Balances\npub fn check_no_negative(accounts: &[(Pubkey, Account)]) -> Vec<String> {\n    accounts.iter().filter(|(_, a)| a.lamports == 0 && a.data.is_empty()).map(|(pk, _)| format!(\"Account {pk} appears drained\")).collect()\n}\n",
        );
    }

    out.push_str(
        "/// Authority Immutability\npub fn check_authority_immutability(before: &[(Pubkey, Account)], after: &[(Pubkey, Account)]) -> Vec<String> {\n    let mut violations = Vec::new();\n    for ((pk_before, acct_before), (_, acct_after)) in before.iter().zip(after.iter()) {\n        if acct_before.owner != acct_after.owner {\n            violations.push(format!(\"Account {pk_before} owner changed from {} to {}\", acct_before.owner, acct_after.owner));\n        }\n    }\n    violations\n}\n",
    );

    if config.has_state_init_flag {
        out.push_str(
            "/// State Integrity\npub fn check_state_integrity(before: &[(Pubkey, Account)], after: &[(Pubkey, Account)], discriminator: &[u8; 8]) -> Vec<String> {\n    let mut violations = Vec::new();\n    for ((pk, acct_before), (_, acct_after)) in before.iter().zip(after.iter()) {\n        if acct_before.data.len() < 9 || acct_after.data.len() < 9 { continue; }\n        if &acct_before.data[..8] != discriminator { continue; }\n        let was_init = acct_before.data[8] != 0;\n        let is_init = acct_after.data[8] != 0;\n        if was_init && !is_init { violations.push(format!(\"Account {pk} was de-initialized (true -> false)\")); }\n    }\n    violations\n}\n",
        );
    }

    out
}

fn render_invariant_checks(config: &FuzzerConfig) -> String {
    let mut out = String::new();

    if config.has_token {
        out.push_str("    // Token supply preservation\n    // TODO: track token balances before/after\n");
    }
    if config.has_vault {
        out.push_str("    // Vault balance consistency\n    // TODO: verify vault >= sum(deposits)\n");
    }
    if config.has_token || config.has_vault {
        out.push_str("    // No negative balances\n    let drained = check_no_negative(accounts_snapshot);\n    violations.extend(drained);\n");
    }
    out.push_str("    // Authority immutability\n    // TODO: take before snapshot and compare\n");
    if config.has_state_init_flag {
        out.push_str("    // State integrity\n    // TODO: check is_initialized doesn't go true->false\n");
    }

    out
}

fn to_pascal_case(name: &str) -> String {
    name.split('_')
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().chain(chars).collect(),
                None => String::new(),
            }
        })
        .collect()
}

fn update_workspace_cargo() -> Result<()> {
    let workspace_toml = PathBuf::from("Cargo.toml");
    if !workspace_toml.exists() {
        return Ok(());
    }
    if fs::read_to_string(&workspace_toml)?.contains("\"fuzzer\"") {
        return Ok(());
    }
    let content = fs::read_to_string(&workspace_toml)?;
    let mut new_content = String::new();
    for line in content.lines() {
        new_content.push_str(line);
        new_content.push('\n');
        if line.trim() == "members = [" {
            new_content.push_str("    \"fuzzer\",\n");
        }
    }
    if new_content != content {
        fs::write(&workspace_toml, &new_content)?;
        ui::print_notice("Added fuzzer to workspace members in Cargo.toml");
    }
    Ok(())
}

fn render_fuzz_target(config: &FuzzerConfig) -> String {
    let date = chrono::Local::now().format("%Y-%m-%d");
    format!(
        r#"// Auto-generated fuzz target for {prog} — {date}

#![no_main]

use libfuzzer_sys::fuzz_target;
use arbitrary::Arbitrary;

use fuzzer_{prog}::{{FuzzInstruction, set_up_program_test, check_invariants}};
use {lib_name}::entry;

use solana_program_test::*;
use solana_sdk::{{signer::keypair::Keypair, transaction::Transaction}};

#[derive(Arbitrary, Debug)]
struct FuzzInput {{
    instructions: Vec<FuzzInstruction>,
}}

fuzz_target!(|input: FuzzInput| {{
    let rt = tokio::runtime::Runtime::new().unwrap();
    rt.block_on(async {{
        let mut program_test = set_up_program_test();
        let (mut banks_client, payer, recent_blockhash) = program_test.start().await;

        let mut trace = Vec::new();
        for ix in &input.instructions {{
            let instruction = ix.to_instruction();
            let mut transaction = Transaction::new_with_payer(&[instruction], Some(&payer.pubkey()));
            transaction.sign(&[&payer], recent_blockhash);

            if banks_client.process_transaction(transaction).await.is_err() {{
                break;
            }}

            trace.push(ix.clone());

            let snapshot = Vec::new();
            if let Err(violations) = check_invariants(&mut banks_client, &payer, &snapshot, &trace) {{
                panic!("Invariant violation:\n{{}}", violations.join("\n"));
            }}
        }}
    }});
}});
"#,
        prog = config.program_name,
        date = date,
        lib_name = config.program_lib_name,
    )
}

// ── Run ───────────────────────────────────────────────────────────────────────

pub fn run() -> Result<()> {
    ui::print_banner();
    ui::print_section_header("Fuzz Execution");

    let fuzzer_dir = PathBuf::from(FUZZER_DIR);
    if !fuzzer_dir.join("Cargo.toml").exists() {
        ui::print_warning("No fuzzer crate found. Run `sat fuzz init` first.");
        return Ok(());
    }

    ui::print_notice("Building fuzzer...");
    let build_status = Command::new("cargo")
        .args(["build", "--release"])
        .current_dir(&fuzzer_dir)
        .status()
        .context("Failed to build fuzzer crate")?;

    if !build_status.success() {
        ui::print_warning("Fuzzer build failed. Review compilation errors above.");
        ui::print_notice("The generated template requires manual configuration:");
        ui::print_notice("  1. PROGRAM_ID in fuzzer/src/lib.rs");
        ui::print_notice("  2. Instruction data in to_instruction() match arms");
        ui::print_notice("  3. Account setup in the fuzz target");
        return Ok(());
    }

    ui::print_success("Fuzzer built successfully.");
    println!();
    ui::print_notice("Running fuzzer (Ctrl+C to stop)...");
    println!();

    let status = Command::new("cargo")
        .args(["fuzz", "run", "instruction_fuzz", "--", "-max_total_time=60"])
        .current_dir(&fuzzer_dir)
        .status()
        .context("Failed to run fuzzer")?;

    if status.success() {
        ui::print_success("Fuzz run completed without crashes.");
    } else {
        ui::print_warning("Fuzz run exited with errors. Check output for crash details.");
    }

    Ok(())
}
