use crate::analyzer::AccountsStruct;
use crate::native::model::NativeProgram;
use crate::types::{Finding, Severity};
use std::collections::HashMap;

// ── Transaction report correlation ────────────────────────────────────────────

#[derive(Debug, Clone, serde::Deserialize)]
#[allow(dead_code)]
struct TxReport {
    #[serde(default)]
    schema_version: String,
    #[serde(default)]
    program_name: String,
    #[serde(default)]
    instructions: Vec<TxReportInstruction>,
}

#[derive(Debug, Clone, serde::Deserialize)]
#[allow(dead_code)]
struct TxReportInstruction {
    #[serde(default)]
    name: String,
    #[serde(default)]
    accounts: Vec<TxReportAccount>,
}

#[derive(Debug, Clone, serde::Deserialize)]
#[allow(dead_code)]
struct TxReportAccount {
    #[serde(default)]
    name: String,
    #[serde(default)]
    is_signer: bool,
    #[serde(default)]
    is_writable: bool,
    #[serde(default)]
    pda_info: Option<TxReportPda>,
}

#[derive(Debug, Clone, serde::Deserialize)]
#[allow(dead_code)]
struct TxReportPda {
    #[serde(default)]
    seeds_declared: Vec<String>,
    #[serde(default)]
    bump: Option<u8>,
}

/// Normalize names for comparison: Anchor IDL instruction names are
/// snake_case while `#[derive(Accounts)]` struct names are PascalCase.
fn normalize_name(s: &str) -> String {
    s.to_lowercase().replace('_', "")
}

/// Load and parse a transaction report, converting read/parse failures into
/// Informational findings (shared by the Anchor and native correlation paths).
#[allow(clippy::result_large_err)]
fn load_tx_report(tx_report_path: &str) -> Result<TxReport, Finding> {
    let content = std::fs::read_to_string(tx_report_path).map_err(|e| Finding {
        id: String::new(),
        title: format!("Failed to read tx-report: {e}"),
        severity: Severity::Informational,
        description: format!("Could not read transaction report file: {tx_report_path}"),
        location: Some(tx_report_path.to_string()),
        suggestion: Some("Verify the file path and permissions.".to_string()),
    })?;
    serde_json::from_str(&content).map_err(|e| Finding {
        id: String::new(),
        title: format!("Failed to parse tx-report: {e}"),
        severity: Severity::Informational,
        description: format!("Transaction report JSON is invalid: {tx_report_path}"),
        location: Some(tx_report_path.to_string()),
        suggestion: Some("Ensure the report was generated by the `rts` tool.".to_string()),
    })
}

pub fn check_tx_report_correlation(accounts: &[AccountsStruct], tx_report_path: &str) -> Vec<Finding> {
    let mut findings = Vec::new();

    let report = match load_tx_report(tx_report_path) {
        Ok(report) => report,
        Err(finding) => return vec![finding],
    };

    let accounts_map: HashMap<String, &AccountsStruct> =
        accounts.iter().map(|a| (normalize_name(&a.name), a)).collect();

    for tx_ix in &report.instructions {
        let ix_name = normalize_name(&tx_ix.name);
        if ix_name.is_empty() {
            // No usable instruction name — correlation cannot match.
            continue;
        }

        let matching_accts: Vec<&&AccountsStruct> = accounts_map
            .values()
            .filter(|accts| {
                let accts_name = normalize_name(&accts.name);
                accts_name == ix_name || ix_name.ends_with(&accts_name) || accts_name.ends_with(&ix_name)
            })
            .collect();

        if matching_accts.is_empty() {
            continue;
        }

        for &accts in &matching_accts {
            for tx_acct in &tx_ix.accounts {
                let tx_name = normalize_name(&tx_acct.name);
                if tx_name.is_empty() {
                    continue;
                }
                if let Some(field) = accts.fields.iter().find(|f| normalize_name(&f.name) == tx_name) {
                    if field.has_signer && !tx_acct.is_signer {
                        findings.push(Finding {
                            id: String::new(),
                            title: format!(
                                "Tx-Report Mismatch: `{}::{}` declared with `#[account(signer)]` but `is_signer = false` in transaction",
                                accts.name, field.name
                            ),
                            severity: Severity::Critical,
                            description: format!(
                                "At runtime, the account `{}` in instruction `{}` was NOT a signer, \
                                 but it is declared with `#[account(signer)]` in `{}`. This means the \
                                 signer constraint was either bypassed or the transaction was crafted \
                                 to exploit a missing runtime check.",
                                field.name, tx_ix.name, accts.name
                            ),
                            location: Some(format!("Tx-report: {} / {}", tx_ix.name, field.name)),
                            suggestion: Some(
                                "Verify that the `#[account(signer)]` constraint is correctly enforced \
                                 at the Anchor framework level and that the runtime account substitution \
                                 is not possible."
                                    .to_string(),
                            ),
                        });
                    }

                    if field.has_mut && !tx_acct.is_writable {
                        findings.push(Finding {
                            id: String::new(),
                            title: format!(
                                "Tx-Report Mismatch: `{}::{}` declared with `#[account(mut)]` but `is_writable = false` in transaction",
                                accts.name, field.name
                            ),
                            severity: Severity::High,
                            description: format!(
                                "At runtime, the account `{}` in instruction `{}` was NOT writable, \
                                 but it is declared with `#[account(mut)]` in `{}`. This may cause \
                                 runtime failures or indicate a deserialization mismatch.",
                                field.name, tx_ix.name, accts.name
                            ),
                            location: Some(format!("Tx-report: {} / {}", tx_ix.name, field.name)),
                            suggestion: Some(
                                "Ensure the account at runtime has the expected writable permissions."
                                    .to_string(),
                            ),
                        });
                    }
                }
            }
        }
    }

    findings
}

/// Correlate a transaction report against a NATIVE program's source-derived
/// model (no Anchor IDL / Accounts struct needed). Mirrors the IDL path:
/// - instruction matched by normalized name (`normalize_name`, handles the
///   frontend's `instruction_0x<tag>` fallback names too)
/// - per account: signer-expected (`ResolvedAccount::is_signer_expected`)
///   that is not a signer in the tx → Critical; written (`written`) account
///   that is not writable in the tx → High
/// - account located by normalized name, falling back to positional
///   `ResolvedAccount.index` (the 1:1 AccountMeta-order contract)
pub fn check_native_tx_report_correlation(program: &NativeProgram, tx_report_path: &str) -> Vec<Finding> {
    let report = match load_tx_report(tx_report_path) {
        Ok(report) => report,
        Err(finding) => return vec![finding],
    };

    let mut findings = Vec::new();

    for tx_ix in &report.instructions {
        let ix_name = normalize_name(&tx_ix.name);
        if ix_name.is_empty() {
            continue;
        }

        let native_ix = match program.instructions.iter().find(|ix| normalize_name(&ix.name) == ix_name) {
            Some(ix) => ix,
            None => continue,
        };

        for native_account in &native_ix.accounts {
            let tx_acct = tx_ix
                .accounts
                .iter()
                .find(|a| !a.name.is_empty() && normalize_name(&a.name) == normalize_name(&native_account.name))
                .or_else(|| tx_ix.accounts.get(native_account.index));
            let Some(tx_acct) = tx_acct else { continue };

            if native_account.is_signer_expected() && !tx_acct.is_signer {
                findings.push(Finding {
                    id: String::new(),
                    title: format!(
                        "Tx-Report Mismatch: `{}` account `{}` requires a signature (source signer guard) but `is_signer = false` in transaction",
                        native_ix.name, native_account.name
                    ),
                    severity: Severity::Critical,
                    description: format!(
                        "At runtime, the account `{}` in instruction `{}` was NOT a signer, but the native \
                         source guards it with a signer check. This means the signer constraint was either \
                         bypassed or the transaction was crafted to exploit a missing runtime check.",
                        native_account.name, tx_ix.name
                    ),
                    location: Some(format!("Tx-report: {} / {}", tx_ix.name, native_account.name)),
                    suggestion: Some(
                        "Verify that the signer guard is correctly enforced at runtime and that account \
                         substitution is not possible."
                            .to_string(),
                    ),
                });
            }

            if native_account.written && !tx_acct.is_writable {
                findings.push(Finding {
                    id: String::new(),
                    title: format!(
                        "Tx-Report Mismatch: `{}` account `{}` is written by the program but `is_writable = false` in transaction",
                        native_ix.name, native_account.name
                    ),
                    severity: Severity::High,
                    description: format!(
                        "At runtime, the account `{}` in instruction `{}` was NOT writable, but the program \
                         source writes to it. This may cause runtime failures or indicate a deserialization mismatch.",
                        native_account.name, tx_ix.name
                    ),
                    location: Some(format!("Tx-report: {} / {}", tx_ix.name, native_account.name)),
                    suggestion: Some(
                        "Ensure the account at runtime has the expected writable permissions."
                            .to_string(),
                    ),
                });
            }
        }
    }

    findings
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::native::analyze_source_for_test;

    const NATIVE_SOURCE: &str = r#"
use solana_program::{
    account_info::{next_account_info, AccountInfo},
    entrypoint,
    entrypoint::ProgramResult,
    program_error::ProgramError,
    pubkey::Pubkey,
};

entrypoint!(process_instruction);

pub fn process_instruction(
    _program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    match instruction_data[0] {
        0 => process_transfer(accounts),
        1 => process_update(accounts),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

fn process_transfer(accounts: &[AccountInfo]) -> ProgramResult {
    let accounts_iter = &mut accounts.iter();

    let from = next_account_info(accounts_iter)?;
    let authority = next_account_info(accounts_iter)?;
    let vault = next_account_info(accounts_iter)?;

    if !authority.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    let mut data = vault.data.borrow_mut();
    data[0] = 1;

    Ok(())
}

fn process_update(accounts: &[AccountInfo]) -> ProgramResult {
    let accounts_iter = &mut accounts.iter();

    let state = next_account_info(accounts_iter)?;
    let authority = next_account_info(accounts_iter)?;

    if !authority.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    Ok(())
}
"#;

    fn write_report(dir: &tempfile::TempDir, json: &str) -> String {
        let path = dir.path().join("report.json");
        std::fs::write(&path, json).unwrap();
        path.to_string_lossy().to_string()
    }

    #[test]
    fn native_signer_mismatch_critical() {
        let program = analyze_source_for_test(NATIVE_SOURCE);
        assert_eq!(program.instructions.len(), 2);
        assert!(program.instructions[0].accounts[1].is_signer_expected());
        assert!(program.instructions[0].accounts[2].written);

        let dir = tempfile::tempdir().unwrap();
        let report = write_report(
            &dir,
            r#"{"instructions": [{"name": "instruction_0x00", "accounts": [
                {"name": "from", "is_signer": false, "is_writable": true},
                {"name": "authority", "is_signer": false, "is_writable": false},
                {"name": "vault", "is_signer": false, "is_writable": true}
            ]}]}"#,
        );

        let findings = check_native_tx_report_correlation(&program, &report);
        assert_eq!(findings.len(), 1);
        assert!(findings[0].title.contains("Tx-Report Mismatch"));
        assert_eq!(findings[0].severity, Severity::Critical);
        assert!(findings[0].description.contains("authority"));
    }

    #[test]
    fn native_writable_mismatch_high() {
        let program = analyze_source_for_test(NATIVE_SOURCE);
        assert_eq!(program.instructions.len(), 2);
        assert!(program.instructions[0].accounts[1].is_signer_expected());
        assert!(program.instructions[0].accounts[2].written);

        let dir = tempfile::tempdir().unwrap();
        let report = write_report(
            &dir,
            r#"{"instructions": [{"name": "instruction_0x00", "accounts": [
                {"name": "from", "is_signer": false, "is_writable": true},
                {"name": "authority", "is_signer": true, "is_writable": false},
                {"name": "vault", "is_signer": false, "is_writable": false}
            ]}]}"#,
        );

        let findings = check_native_tx_report_correlation(&program, &report);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].severity, Severity::High);
        assert!(findings[0].description.contains("vault"));
    }

    #[test]
    fn native_clean_report_no_findings() {
        let program = analyze_source_for_test(NATIVE_SOURCE);
        assert_eq!(program.instructions.len(), 2);
        assert!(program.instructions[0].accounts[1].is_signer_expected());
        assert!(program.instructions[0].accounts[2].written);

        let dir = tempfile::tempdir().unwrap();
        let report = write_report(
            &dir,
            r#"{"instructions": [{"name": "instruction_0x00", "accounts": [
                {"name": "from", "is_signer": false, "is_writable": true},
                {"name": "authority", "is_signer": true, "is_writable": false},
                {"name": "vault", "is_signer": false, "is_writable": true}
            ]}]}"#,
        );

        let findings = check_native_tx_report_correlation(&program, &report);
        assert!(findings.is_empty());
    }

    #[test]
    fn native_unknown_instruction_skipped() {
        let program = analyze_source_for_test(NATIVE_SOURCE);
        assert_eq!(program.instructions.len(), 2);
        assert!(program.instructions[0].accounts[1].is_signer_expected());
        assert!(program.instructions[0].accounts[2].written);

        let dir = tempfile::tempdir().unwrap();
        let report = write_report(
            &dir,
            r#"{"instructions": [{"name": "nope_ix", "accounts": [
                {"name": "from", "is_signer": false, "is_writable": true},
                {"name": "authority", "is_signer": false, "is_writable": false}
            ]}]}"#,
        );

        let findings = check_native_tx_report_correlation(&program, &report);
        assert!(findings.is_empty());
    }
}
