use crate::analyzer::AccountsStruct;
use crate::types::{Finding, Severity};
use std::collections::HashMap;

// ── Transaction report correlation ────────────────────────────────────────────

#[derive(Debug, Clone, serde::Deserialize)]
#[allow(dead_code)]
struct TxReport {
    #[serde(default)]
    schema_version: String,
    #[serde(default)]
    program_name: String,
    #[serde(default)]
    instructions: Vec<TxReportInstruction>,
}

#[derive(Debug, Clone, serde::Deserialize)]
#[allow(dead_code)]
struct TxReportInstruction {
    #[serde(default)]
    name: String,
    #[serde(default)]
    accounts: Vec<TxReportAccount>,
}

#[derive(Debug, Clone, serde::Deserialize)]
#[allow(dead_code)]
struct TxReportAccount {
    #[serde(default)]
    name: String,
    #[serde(default)]
    is_signer: bool,
    #[serde(default)]
    is_writable: bool,
    #[serde(default)]
    pda_info: Option<TxReportPda>,
}

#[derive(Debug, Clone, serde::Deserialize)]
#[allow(dead_code)]
struct TxReportPda {
    #[serde(default)]
    seeds_declared: Vec<String>,
    #[serde(default)]
    bump: Option<u8>,
}

pub(crate) fn check_tx_report_correlation(accounts: &[AccountsStruct], tx_report_path: &str) -> Vec<Finding> {
    let mut findings = Vec::new();

    let content = match std::fs::read_to_string(tx_report_path) {
        Ok(c) => c,
        Err(e) => {
            findings.push(Finding {
                id: String::new(),
                title: format!("Failed to read tx-report: {e}"),
                severity: Severity::Informational,
                description: format!("Could not read transaction report file: {tx_report_path}"),
                location: Some(tx_report_path.to_string()),
                suggestion: Some("Verify the file path and permissions.".to_string()),
            });
            return findings;
        }
    };

    let report: TxReport = match serde_json::from_str(&content) {
        Ok(r) => r,
        Err(e) => {
            findings.push(Finding {
                id: String::new(),
                title: format!("Failed to parse tx-report: {e}"),
                severity: Severity::Informational,
                description: format!("Transaction report JSON is invalid: {tx_report_path}"),
                location: Some(tx_report_path.to_string()),
                suggestion: Some("Ensure the report was generated by the `rts` tool.".to_string()),
            });
            return findings;
        }
    };

    let accounts_map: HashMap<String, &AccountsStruct> = accounts.iter().map(|a| (a.name.to_lowercase(), a)).collect();

    for tx_ix in &report.instructions {
        let ix_name_lower = tx_ix.name.to_lowercase();

        let matching_accts: Vec<&&AccountsStruct> = accounts_map
            .values()
            .filter(|accts| {
                accts.name.to_lowercase() == ix_name_lower
                    || ix_name_lower.ends_with(&accts.name.to_lowercase())
                    || accts.name.to_lowercase().ends_with(&ix_name_lower)
            })
            .collect();

        if matching_accts.is_empty() {
            continue;
        }

        for &accts in &matching_accts {
            for tx_acct in &tx_ix.accounts {
                let tx_name_lower = tx_acct.name.to_lowercase();
                if let Some(field) = accts.fields.iter().find(|f| f.name.to_lowercase() == tx_name_lower) {
                    if field.has_signer && !tx_acct.is_signer {
                        findings.push(Finding {
                            id: String::new(),
                            title: format!(
                                "Tx-Report Mismatch: `{}::{}` declared with `#[account(signer)]` but `is_signer = false` in transaction",
                                accts.name, field.name
                            ),
                            severity: Severity::Critical,
                            description: format!(
                                "At runtime, the account `{}` in instruction `{}` was NOT a signer, \
                                 but it is declared with `#[account(signer)]` in `{}`. This means the \
                                 signer constraint was either bypassed or the transaction was crafted \
                                 to exploit a missing runtime check.",
                                field.name, tx_ix.name, accts.name
                            ),
                            location: Some(format!("Tx-report: {} / {}", tx_ix.name, field.name)),
                            suggestion: Some(
                                "Verify that the `#[account(signer)]` constraint is correctly enforced \
                                 at the Anchor framework level and that the runtime account substitution \
                                 is not possible."
                                    .to_string(),
                            ),
                        });
                    }

                    if field.has_mut && !tx_acct.is_writable {
                        findings.push(Finding {
                            id: String::new(),
                            title: format!(
                                "Tx-Report Mismatch: `{}::{}` declared with `#[account(mut)]` but `is_writable = false` in transaction",
                                accts.name, field.name
                            ),
                            severity: Severity::High,
                            description: format!(
                                "At runtime, the account `{}` in instruction `{}` was NOT writable, \
                                 but it is declared with `#[account(mut)]` in `{}`. This may cause \
                                 runtime failures or indicate a deserialization mismatch.",
                                field.name, tx_ix.name, accts.name
                            ),
                            location: Some(format!("Tx-report: {} / {}", tx_ix.name, field.name)),
                            suggestion: Some(
                                "Ensure the account at runtime has the expected writable permissions."
                                    .to_string(),
                            ),
                        });
                    }
                }
            }
        }
    }

    findings
}
