//! Formal verification scaffolding generator (`sat verify init`).
//!
//! Generates a standalone Kani crate (`formal-verification/`) with mock Solana
//! types, representative checked-arithmetic functions, and `#[kani::proof]`
//! harnesses. The crate is intentionally NOT added to the workspace members:
//! it only needs to exist when Kani proofs are run.

use std::fs;
use std::path::PathBuf;

use anyhow::Result;

use crate::idl;
use crate::ui;

const VERIFY_DIR: &str = "formal-verification";

/// Everything the generated crate needs to know about the target program.
#[derive(Debug, Clone)]
struct VerifyConfig {
    program_name: String,
    instruction_names: Vec<String>,
    /// Names of account fields whose IDL type is an integer (u64, u32, ...).
    numeric_fields: Vec<String>,
}

pub fn init() -> anyhow::Result<()> {
    ui::print_banner();
    ui::print_section_header("Verification Initialization");

    let config = match idl::find_idl_in_workspace().ok().and_then(|p| idl::parse_idl(&p).ok()) {
        Some(idl) => config_from_idl(idl),
        None => {
            ui::print_warning("No Anchor IDL found. Generating scaffolding with default configuration...");
            default_config()
        }
    };

    generate_crate(&config)?;

    ui::print_success("Formal verification crate generated at formal-verification/");
    ui::print_notice("Next steps:");
    println!("  1. cd formal-verification");
    println!("  2. Install Kani: cargo install kani-verifier (https://model-checking.github.io/kani/)");
    println!("  3. Replace the math module in src/lib.rs with your program's logic");
    println!("  4. Run: cargo kani");
    println!();
    Ok(())
}

fn config_from_idl(idl: idl::IdlJson) -> VerifyConfig {
    let instruction_names = idl.instructions.iter().map(|ix| ix.name.clone()).collect();

    let mut numeric_fields: Vec<String> = idl
        .accounts
        .iter()
        .flat_map(|account| account.ty.fields.iter())
        .filter(|field| is_numeric_field_type(&field.ty))
        .map(|field| field.name.clone())
        .collect();
    numeric_fields.sort();
    numeric_fields.dedup();

    VerifyConfig { program_name: idl.name, instruction_names, numeric_fields }
}

fn default_config() -> VerifyConfig {
    VerifyConfig { program_name: "program".to_string(), instruction_names: Vec::new(), numeric_fields: Vec::new() }
}

/// True when the IDL type is a plain integer primitive (e.g. `"u64"`).
fn is_numeric_field_type(ty: &serde_json::Value) -> bool {
    matches!(ty.as_str(), Some("u8" | "u16" | "u32" | "u64" | "u128" | "i8" | "i16" | "i32" | "i64" | "i128"))
}

fn generate_crate(config: &VerifyConfig) -> Result<()> {
    let dir = PathBuf::from(VERIFY_DIR);
    fs::create_dir_all(dir.join("src"))?;

    fs::write(dir.join("Cargo.toml"), render_cargo_toml())?;
    fs::write(dir.join("src").join("lib.rs"), render_lib_rs(config))?;
    fs::write(dir.join("src").join("proofs.rs"), render_proofs_rs(config))?;
    fs::write(dir.join("README.md"), render_readme(config))?;
    Ok(())
}

fn render_cargo_toml() -> String {
    r#"[package]
name = "formal-verification"
version = "0.1.0"
edition = "2024"
publish = false

# The kani crate version must match the installed Kani toolchain:
#   cargo install kani-verifier
[dependencies]
kani = { version = "0.72" }
"#
    .to_string()
}

fn render_lib_rs(config: &VerifyConfig) -> String {
    let ix_list = if config.instruction_names.is_empty() {
        "none detected (add them as you wire the crate)".to_string()
    } else {
        config.instruction_names.join(", ")
    };
    let invariant_comment = if config.numeric_fields.is_empty() {
        String::new()
    } else {
        format!("// Candidate fields for state invariants: {}\n", config.numeric_fields.join(", "))
    };

    format!(
        r#"//! Kani formal-verification scaffolding for `{prog}`.
//!
//! Auto-generated by `sat verify init`. This crate compiles standalone: the
//! mock types below replace the Solana runtime types so the proofs in
//! [`proofs`] run without the runtime.
//!
//! Program: {prog}
//! Instructions: {ix_list}
#![allow(dead_code)] // mock scaffolding is unused until wired to the program

/// Mock of `solana_program::account_info::AccountInfo`.
///
/// Replaces the runtime type so proofs can run without the Solana runtime.
pub struct AccountInfo {{
    pub key: [u8; 32],
    pub lamports: u64,
    pub data: Vec<u8>,
    pub owner: [u8; 32],
}}

/// Mock of `solana_program::clock::Clock`.
///
/// Replaces the runtime type so proofs can run without the Solana runtime.
pub struct Clock {{
    pub unix_timestamp: i64,
    pub slot: u64,
    pub epoch: u64,
}}

/// Mock of `solana_program::rent::Rent`.
///
/// Replaces the runtime type so proofs can run without the Solana runtime.
pub struct Rent {{
    pub lamports_per_byte_year: u64,
}}

{invariant_comment}/// Representative checked-arithmetic functions.
///
/// REPLACE with your program's functions: the harnesses in [`proofs`] verify
/// whatever lives here.
pub mod math {{
    /// Returns `amount * basis_points / 10000`, or `None` on overflow.
    ///
    /// REPLACE with your program's real fee logic.
    pub fn fee_amount(amount: u64, basis_points: u64) -> Option<u64> {{
        let scaled = amount.checked_mul(basis_points)?;
        scaled.checked_div(10000)
    }}

    /// Example balance update: credits then debits by `delta`, returning
    /// `None` if either step would overflow.
    ///
    /// REPLACE with your program's real update logic.
    pub fn update_balance(balance: u64, delta: u64) -> Option<u64> {{
        let credited = balance.checked_add(delta)?;
        credited.checked_sub(delta)
    }}
}}

/// Kani proof harnesses — see `src/proofs.rs`.
pub mod proofs;
"#,
        prog = config.program_name,
        ix_list = ix_list,
        invariant_comment = invariant_comment,
    )
}

fn render_proofs_rs(config: &VerifyConfig) -> String {
    format!(
        r#"//! Kani proof harnesses for `{prog}`.
//!
//! Run a single harness:
//!   cargo kani --harness fee_amount_never_panics
//!
//! Run all harnesses:
//!   cargo kani
#![allow(dead_code)] // harnesses are executed by Kani, not by normal builds

// The harnesses below use `kani::any()`, which generates an arbitrary value
// of the target type, so Kani explores every possible input — including the
// edge cases fuzzing rarely reaches.

#[kani::proof]
fn fee_amount_never_panics() {{
    let amount: u64 = kani::any();
    let basis_points: u64 = kani::any();
    let _ = crate::math::fee_amount(amount, basis_points);
}}

#[kani::proof]
fn update_balance_never_panics() {{
    let balance: u64 = kani::any();
    let delta: u64 = kani::any();
    let _ = crate::math::update_balance(balance, delta);
}}

// ── Template for your own harnesses ──────────────────────────────────────────
//
// `kani::any()` generates arbitrary inputs, so Kani explores all possible
// values — including the ones fuzzing rarely reaches.
//
// Note: the checked-arithmetic helpers above return `Option`, so their proofs
// hold trivially — Kani has nothing to panic on. The real value comes after
// you wire this crate to your program's actual logic (unwraps, indexing,
// assertions, and invariants over state). Uncomment and adapt this template
// once the `math` module contains your program's functions:
//
// #[kani::proof]
// fn my_function_never_panics() {{
//     let input: u64 = kani::any();
//     let _ = crate::math::my_function(input);
// }}
"#,
        prog = config.program_name,
    )
}

fn render_readme(config: &VerifyConfig) -> String {
    let fields_section = if config.numeric_fields.is_empty() {
        String::new()
    } else {
        format!(
            "## Candidate state invariants\n\nNumeric fields detected in the IDL\nthat are good starting points for state invariants:\n\n    {}\n\n",
            config.numeric_fields.join(", ")
        )
    };

    format!(
        r#"# Formal Verification Scaffolding — {prog}

Auto-generated by `sat verify init`. This standalone crate contains Kani
formal-verification scaffolding: mock Solana types, representative
checked-arithmetic functions, and `#[kani::proof]` harnesses.

## Prerequisites

Install the Kani Rust Verifier: <https://model-checking.github.io/kani/>

The `kani` crate version in `Cargo.toml` must match the installed Kani
toolchain. Install the matching verifier with:

    cargo install kani-verifier

## Usage

Run a single harness:

    cd formal-verification && cargo kani --harness fee_amount_never_panics

Run all harnesses:

    cargo kani

## What was generated

- `Cargo.toml` — standalone crate with the `kani` dependency pinned to the
  toolchain version.
- `src/lib.rs` — mock `AccountInfo`, `Clock`, and `Rent` types plus a `math`
  module with representative checked-arithmetic functions.
- `src/proofs.rs` — `#[kani::proof]` harnesses that feed arbitrary inputs
  via `kani::any()`.

## Honest caveat

The included harnesses prove that the *representative* math stubs never
panic. Because those functions use checked arithmetic and return `Option`,
the proofs hold trivially — Kani has nothing to panic on. The real value
comes after you replace the stubs with your program's actual logic.

## Adapting to your program

1. Replace the `math` module in `src/lib.rs` with your program's functions.
2. Replace the mock types with the real `solana_program` types (or keep the
   mocks and mirror your account layouts).
3. Add harnesses in `src/proofs.rs` that call your functions with
   `kani::any()` inputs and assert your invariants.
4. Run `cargo kani` and iterate on any reachable panics or failed assertions.
{fields_section}
"#,
        prog = config.program_name,
        fields_section = fields_section,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_lib_contains_kani_proof_attr() {
        let config = default_config();
        let proofs = render_proofs_rs(&config);

        assert!(proofs.contains("#[kani::proof]"));
    }

    #[test]
    fn generated_harness_uses_kani_any() {
        let config = default_config();
        let proofs = render_proofs_rs(&config);

        assert!(proofs.contains("kani::any()"));
    }

    #[test]
    fn generated_crate_contains_mock_account_info() {
        let config = default_config();
        let lib = render_lib_rs(&config);

        assert!(lib.contains("struct AccountInfo"));
    }

    #[test]
    fn generated_crate_mentions_math_module() {
        let config = default_config();
        let lib = render_lib_rs(&config);

        assert!(lib.contains("pub mod math"));
    }

    #[test]
    fn generated_readme_has_run_instructions() {
        let config = default_config();
        let readme = render_readme(&config);

        assert!(readme.contains("cargo kani"));
    }
}
