//! Framework-macro dispatch recovery (wormhole solitaire! class): no
//! `entrypoint!`/`process_instruction` marker exists — the entrypoint and
//! dispatch table are both generated by the macro, whose invocation tokens
//! carry `Name(DataType) => handler` rows. The generated `#[repr(u8)]`
//! enum assigns tags in declaration order (borsh order). Accounts stay
//! unresolved (framework-peeled).
//!
//! Note: this fixture only needs to parse with `syn` — it does not need to
//! compile against real `solitaire`/`solana_program` crates.
use solitaire::*;

solitaire! {
    Initialize(InitializeData)                  => initialize,
    PostMessage(PostMessageData)                => post_message,
    PostVAA(PostVAAData)                        => post_vaa,
    SetFees(SetFeesData)                        => set_fees,
    TransferFees(TransferFeesData)              => transfer_fees,
    UpgradeContract(UpgradeContractData)        => upgrade_contract,
    UpgradeGuardianSet(UpgradeGuardianSetData)  => upgrade_guardian_set,
    VerifySignatures(VerifySignaturesData)      => verify_signatures,
}
