//! `marginfi-harness` — records a canonical `parity` trace of the **real**
//! MarginFi lending program (a real, audited, modern-Solana target) running in
//! `solana-program-test`.
//!
//! Generated by `parity emit-harness`; the adapter below maps scenario ops to
//! MarginFi instructions (`try_bank_deposit` / `try_bank_withdraw` via
//! `marginfi-test-utilities`) and maps MarginFi state onto the canonical
//! `Observables` surface.
//!
//! Usage: `marginfi-harness --scenario scenario.json [--out trace.json]`

use std::path::PathBuf;

use anyhow::{Context, Result};
use fixtures::marginfi_account::MarginfiAccountFixture;
use fixtures::prelude::*;
use fixed::types::I80F48;
use marginfi::state::bank::BankImpl;
use serde::{Deserialize, Serialize};

// ── Wire types (mirror parity::Scenario / Trace / Observables) ───────────────

#[derive(Debug, Clone, Deserialize)]
struct Scenario {
    name: String,
    #[serde(default)]
    accounts: Vec<AccountSpec>,
    ops: Vec<Op>,
}

#[derive(Debug, Clone, Deserialize)]
struct AccountSpec {
    #[serde(default)]
    role: String,
    #[serde(default)]
    name: String,
    #[serde(default)]
    initial: u64,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
enum Op {
    Deposit { user: String, amount: u64 },
    Withdraw { user: String, amount: u64 },
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
struct Observables {
    total_deposits: u64,
    total_borrows: u64,
    total_shares: u64,
    vault_balance: u64,
    user_shares: u64,
    user_balance: u64,
    price: u64,
}

#[derive(Debug, Clone, Serialize)]
struct TraceStep {
    op_index: usize,
    observables: Observables,
    error: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
struct Trace {
    scenario: String,
    model: String,
    steps: Vec<TraceStep>,
}

// ── Adapter ──────────────────────────────────────────────────────────────────

/// Read MarginFi state into the canonical observables. Shares are expressed in
/// **asset terms** (`get_asset_amount`) so they are comparable to the reference
/// model's 1:1 share accounting when the share value is one.
async fn observe(test_f: &TestFixture, marginfi_account: &MarginfiAccountFixture, token_account: &TokenAccountFixture) -> Observables {
    let bank_f = test_f.get_bank(&BankMint::Usdc);
    let bank = bank_f.load().await;
    let bank_pk = bank_f.key;

    let total_asset_shares = I80F48::from(bank.total_asset_shares);
    let total_liability_shares = I80F48::from(bank.total_liability_shares);
    let total_deposits = bank.get_asset_amount(total_asset_shares).map(|v| v.to_num::<u64>()).unwrap_or(0);
    let total_borrows = bank.get_liability_amount(total_liability_shares).map(|v| v.to_num::<u64>()).unwrap_or(0);

    let vault_balance = balance_of(test_f.context.clone(), bank.liquidity_vault).await;

    let mfi = marginfi_account.load().await;
    let user_shares_assets = mfi
        .lending_account
        .balances
        .iter()
        .find(|b| b.bank_pk == bank_pk)
        .map(|b| bank.get_asset_amount(I80F48::from(b.asset_shares)).map(|v| v.to_num::<u64>()).unwrap_or(0))
        .unwrap_or(0);

    Observables {
        total_deposits,
        total_borrows,
        total_shares: total_deposits,
        vault_balance,
        user_shares: user_shares_assets,
        user_balance: token_account.balance().await,
        price: 1,
    }
}

// ── Runner ───────────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().collect();
    let mut scenario_path: Option<PathBuf> = None;
    let mut out: Option<PathBuf> = None;
    let mut i = 1;
    while i < args.len() {
        match args[i].as_str() {
            "--scenario" => {
                scenario_path = args.get(i + 1).map(PathBuf::from);
                i += 2;
            }
            "--out" => {
                out = args.get(i + 1).map(PathBuf::from);
                i += 2;
            }
            other => anyhow::bail!("unknown argument `{other}` (expected --scenario FILE [--out FILE])"),
        }
    }
    let scenario_path = scenario_path.context("--scenario is required")?;
    let scenario: Scenario = serde_json::from_str(
        &std::fs::read_to_string(&scenario_path).with_context(|| format!("failed to read {}", scenario_path.display()))?,
    )
    .context("invalid scenario JSON")?;

    let bank_mint = BankMint::Usdc;

    // Setup: real MarginFi group + banks + oracles (test-utilities).
    let mut test_f = TestFixture::new(Some(TestSettings::all_banks_payer_not_admin())).await;
    let marginfi_account = test_f.create_marginfi_account().await;
    let token_account = TokenAccountFixture::new(
        test_f.context.clone(),
        &test_f.get_bank(&bank_mint).mint,
        &test_f.payer(),
    )
    .await;

    // Fund the user with exactly the scenario's declared initial balance so the
    // canonical `user_balance` observable is comparable to the reference model.
    let decimals = test_f.get_bank(&bank_mint).load().await.mint_decimals;
    let scale = 10u64.pow(decimals as u32) as f64;
    let user_initial = scenario
        .accounts
        .iter()
        .find(|a| a.role == "user")
        .map(|a| a.initial)
        .unwrap_or(1_000_000_000);
    let funding_ui = user_initial as f64 / scale;
    test_f.get_bank_mut(&bank_mint).mint.mint_to(&token_account.key, funding_ui).await;

    let mut steps = Vec::new();
    for (op_index, op) in scenario.ops.iter().enumerate() {
        let bank_f = test_f.get_bank(&bank_mint);
        let error = match op {
            Op::Deposit { amount, .. } => {
                let ui = *amount as f64 / scale;
                marginfi_account
                    .try_bank_deposit(token_account.key, bank_f, ui, None)
                    .await
                    .err()
                    .map(|e| format!("{e:?}"))
            }
            Op::Withdraw { amount, .. } => {
                let ui = *amount as f64 / scale;
                marginfi_account
                    .try_bank_withdraw(token_account.key, bank_f, ui, None)
                    .await
                    .err()
                    .map(|e| format!("{e:?}"))
            }
        };
        let observables = observe(&test_f, &marginfi_account, &token_account).await;
        steps.push(TraceStep { op_index, observables, error });
    }

    let trace = Trace { scenario: scenario.name.clone(), model: "marginfi".to_string(), steps };
    let json = serde_json::to_string_pretty(&trace)?;
    match out {
        Some(path) => {
            std::fs::write(&path, json).with_context(|| format!("failed to write {}", path.display()))?;
            eprintln!("wrote trace to {}", path.display());
        }
        None => println!("{json}"),
    }
    let _ = scenario.accounts; // account specs are implicit in the MarginFi fixture
    Ok(())
}
